# Generated by Django 5.0.14 on 2025-06-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDH', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Ngay', models.DateField()),
                ('GiaTri', models.FloatField()),
                ('TrangThaiTT', models.CharField(max_length=100)),
                ('TrangThaiGH', models.CharField(max_length=100)),
                ('PTTT', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('MaGH', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('MaDM', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('TenDM', models.CharField(max_length=100)),
                ('DanhMucCha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='DiaChi',
            fields=[
                ('MaDC', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=100)),
                ('Ho', models.CharField(max_length=100)),
                ('CongTy', models.CharField(max_length=100)),
                ('DiaChi1', models.CharField(max_length=100)),
                ('DiaChi2', models.CharField(max_length=100)),
                ('QuocGia', models.CharField(max_length=100)),
                ('MaZip', models.CharField(max_length=20)),
                ('SoDienThoai', models.CharField(max_length=100)),
                ('MaDH', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.donhang')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSp', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('TenSp', models.CharField(max_length=100)),
                ('HangSX', models.CharField(max_length=100)),
                ('Gia', models.FloatField()),
                ('CPU', models.CharField(max_length=500)),
                ('Ram', models.CharField(max_length=100)),
                ('OCung', models.CharField(max_length=100)),
                ('Card', models.CharField(max_length=100)),
                ('DVD', models.CharField(max_length=100)),
                ('Keyboard', models.CharField(max_length=100)),
                ('PhanLoai', models.CharField(max_length=100)),
                ('CongIOsau', models.CharField(max_length=500)),
                ('CongXuatTrinh', models.CharField(max_length=100)),
                ('Wifi_Bluetooth', models.CharField(max_length=100)),
                ('LAN', models.CharField(max_length=100)),
                ('CongIOtruoc', models.CharField(max_length=500)),
                ('KichThuoc', models.CharField(max_length=100)),
                ('KhoiLuong', models.CharField(max_length=100)),
                ('HDH', models.CharField(max_length=100)),
                ('BaoHanh', models.IntegerField(default=0)),
                ('MaDM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('MaKM', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('NgayBatDau', models.DateField()),
                ('NgayKetThuc', models.DateField()),
                ('PhanTram', models.DecimalField(decimal_places=2, max_digits=5)),
                ('MaSp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='HinhAnh',
            fields=[
                ('MaHA', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('MaSp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='GioHang_SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.PositiveIntegerField(default=1)),
                ('GioHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.giohang')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.sanpham')),
            ],
            options={
                'unique_together': {('GioHang', 'SanPham')},
            },
        ),
        migrations.AddField(
            model_name='giohang',
            name='SanPham',
            field=models.ManyToManyField(through='payment.GioHang_SanPham', to='payment.sanpham'),
        ),
        migrations.CreateModel(
            name='DonHang_SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.PositiveIntegerField(default=1)),
                ('DonHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.donhang')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.sanpham')),
            ],
            options={
                'unique_together': {('DonHang', 'SanPham')},
            },
        ),
        migrations.AddField(
            model_name='donhang',
            name='MaSP',
            field=models.ManyToManyField(through='payment.DonHang_SanPham', to='payment.sanpham'),
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('MaTK', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('MatKhau', models.CharField(max_length=100)),
                ('MaDC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.diachi')),
            ],
        ),
        migrations.AddField(
            model_name='giohang',
            name='TaiKhoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.taikhoan'),
        ),
    ]
