from .homePage import homePage
from .timkiem import timkiem_view
from .giohang import giohang_view
from .intro import intro_view
from .news import news_view
from .onlineBill import onlineBill_view
from .recruitment import recruitment_view
from .dangnhap import dangnhap_view
from .dangky import dangky_view
from .dangxuat import dangxuat_view
from .accountInfo import account_info_view
from .address import address_view
from .chiTietSp import chiTietSp_view
from .payment import payment_view
from .giohang import add_to_cart_view
from .updateCart import update_cart_view