# Generated by Django 5.0.14 on 2025-06-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='CongIOsau',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='CongIOtruoc',
            field=models.CharField(max_length=500),
        ),
    ]
