# Generated by Django 5.0.14 on 2025-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_hinhanh_matt_remove_hinhanh_madm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khuyenmai',
            old_name='MaSP',
            new_name='MaSp',
        ),
    ]
