# Generated by Django 5.0.14 on 2025-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_sanpham_congiosau_alter_sanpham_congiotruoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='CPU',
            field=models.CharField(max_length=500),
        ),
    ]
