# Generated by Django 5.0.14 on 2025-06-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_sanpham_cpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hinhanh',
            name='MaTT',
        ),
        migrations.RemoveField(
            model_name='hinhanh',
            name='MaDM',
        ),
        migrations.DeleteModel(
            name='TinTuc',
        ),
    ]
